admin_homepage:
    pattern:  /
    defaults: { _controller: IOAdminBundle:Default:index }

admin_restaurants:
    pattern:  /restaurants
    defaults: { _controller: IOAdminBundle:Restaurant:index }

admin_restaurant_new:
    pattern:  /restaurant/new
    defaults: { _controller: IOAdminBundle:Restaurant:new }

admin_users:
    pattern:  /users
    defaults: { _controller: IOAdminBundle:User:index }

admin_user_new:
    pattern:  /user/new
    defaults: { _controller: IOAdminBundle:User:new }
