menu_show:
    pattern:  /{id}/show
    defaults: { _controller: "IOCarteBundle:Menu:show" }

menu_new:
    pattern:  /new
    defaults: { _controller: "IOCarteBundle:Menu:new" }

menu_create:
    pattern:  /create
    defaults: { _controller: "IOCarteBundle:Menu:create" }
    requirements: { _method: post }

menu_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "IOCarteBundle:Menu:edit" }

menu_update:
    pattern:  /{id}/update
    defaults: { _controller: "IOCarteBundle:Menu:update" }
    requirements: { _method: post|put }

menu_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "IOCarteBundle:Menu:delete" }
    requirements: { _method: post|delete }
