<?php

namespace IO\CommandeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeLineRepository extends EntityRepository
{
}
