dish_new:
    pattern:  /new
    defaults: { _controller: "IOMenuBundle:Dish:new" }

dish_create:
    pattern:  /create
    defaults: { _controller: "IOMenuBundle:Dish:create" }
    requirements: { _method: post }

dish_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "IOMenuBundle:Dish:edit" }

dish_update:
    pattern:  /{id}/update
    defaults: { _controller: "IOMenuBundle:Dish:update" }
    requirements: { _method: post|put }

dish_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "IOMenuBundle:Dish:delete" }
    requirements: { _method: post|delete }
