<?php

namespace IO\OrderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrderMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderMenuRepository extends EntityRepository
{
    
}
